[package]
name = "sunburst_hasher"
version = "0.1.0"
authors = ["Tim Blazytko <tim@blazytko.to>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
structopt="*"
